name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          bubblewrap init --manifest https://imransir09.github.io/PM-POSHAN-PRO-V2/manifest.json --directory twa --skipPwaValidation
          cd twa
          bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pm-poshan-apk
          path: twa/app-release-signed.apk
